baseURL = 'http://localhost:1313/'
languageCode = 'en-us'
title = 'DESIGN.JAMESCUBE.work'
theme = [] 

[module]
  [[module.imports]]
    path = "github.com/nicokaiser/hugo-theme-gallery/v4"

[params]
  defaultTheme = "dark"