baseURL = 'http://localhost:1313/'
languageCode = 'en-us'
title = 'DESIGN.JAMESCUBE.work'
theme = 'Berenice'

timeout = '120s'

[params]
  [params.author]
    name = 'James Jeong'
    email = 'jamescube87@gmail.com'